"""create ai_logs table

Revision ID: 008
Revises: 007
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '008'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('detection_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('bbox_x', sa.Float(), nullable=True),
    sa.Column('bbox_y', sa.Float(), nullable=True),
    sa.Column('bbox_width', sa.Float(), nullable=True),
    sa.Column('bbox_height', sa.Float(), nullable=True),
    sa.Column('detection_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('violation_type', sa.String(length=100), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('is_violation', sa.Boolean(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_camera_id'), 'ai_logs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_id'), 'ai_logs', ['id'], unique=False)
    op.create_index('ix_ai_logs_timestamp', 'ai_logs', ['timestamp'], unique=False)
    op.create_index('ix_ai_logs_detection_type', 'ai_logs', ['detection_type'], unique=False)
    op.create_index('ix_ai_logs_is_violation', 'ai_logs', ['is_violation'], unique=False)
    op.create_index('ix_ai_logs_license_plate', 'ai_logs', ['license_plate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_logs_license_plate', table_name='ai_logs')
    op.drop_index('ix_ai_logs_is_violation', table_name='ai_logs')
    op.drop_index('ix_ai_logs_detection_type', table_name='ai_logs')
    op.drop_index('ix_ai_logs_timestamp', table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_camera_id'), table_name='ai_logs')
    op.drop_table('ai_logs')
    # ### end Alembic commands ###