"""initial schema

Revision ID: 38cd60aa1013
Revises: 
Create Date: 2025-12-25 13:28:56.199472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38cd60aa1013'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('camera_type', sa.String(length=100), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('enabled_detections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model_version', sa.String(length=100), nullable=True),
    sa.Column('confidence_threshold', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('last_maintenance', sa.Date(), nullable=True),
    sa.Column('next_maintenance', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('confidence_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('score_range', sa.String(length=20), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=True),
    sa.Column('approval_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('avg_processing_time', sa.Integer(), nullable=True),
    sa.Column('false_positive_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('true_positive_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_analytics_analysis_date'), 'confidence_analytics', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_confidence_analytics_id'), 'confidence_analytics', ['id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('total_violations', sa.Integer(), nullable=True),
    sa.Column('approved_violations', sa.Integer(), nullable=True),
    sa.Column('rejected_violations', sa.Integer(), nullable=True),
    sa.Column('pending_violations', sa.Integer(), nullable=True),
    sa.Column('violation_type_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score_avg', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('total_revenue', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('collected_revenue', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('pending_revenue', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('new_users', sa.Integer(), nullable=True),
    sa.Column('total_complaints', sa.Integer(), nullable=True),
    sa.Column('resolved_complaints', sa.Integer(), nullable=True),
    sa.Column('approval_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('collection_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_id'), 'daily_stats', ['id'], unique=False)
    op.create_index(op.f('ix_daily_stats_stat_date'), 'daily_stats', ['stat_date'], unique=True)
    op.create_table('location_hotspots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('total_violations', sa.Integer(), nullable=True),
    sa.Column('violation_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revenue_generated', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('risk_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('trend_direction', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_hotspots_id'), 'location_hotspots', ['id'], unique=False)
    op.create_index(op.f('ix_location_hotspots_location_name'), 'location_hotspots', ['location_name'], unique=False)
    op.create_index(op.f('ix_location_hotspots_period_date'), 'location_hotspots', ['period_date'], unique=False)
    op.create_table('model_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('precision_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('recall_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('f1_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('accuracy', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('avg_processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('total_predictions', sa.Integer(), nullable=True),
    sa.Column('performance_by_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_performance_evaluation_date'), 'model_performance', ['evaluation_date'], unique=False)
    op.create_index(op.f('ix_model_performance_id'), 'model_performance', ['id'], unique=False)
    op.create_index(op.f('ix_model_performance_model_name'), 'model_performance', ['model_name'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_code', sa.String(length=100), nullable=True),
    sa.Column('notification_type', sa.Enum('VIOLATION_ALERT', 'PAYMENT_REMINDER', 'PAYMENT_CONFIRMATION', 'COMPLAINT_UPDATE', 'APPEAL_RESULT', 'SYSTEM_ANNOUNCEMENT', 'SECURITY_ALERT', name='notificationtype'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('subject_template', sa.String(length=500), nullable=True),
    sa.Column('email_template', sa.Text(), nullable=True),
    sa.Column('sms_template', sa.Text(), nullable=True),
    sa.Column('push_template', sa.Text(), nullable=True),
    sa.Column('web_template', sa.Text(), nullable=True),
    sa.Column('default_channel', sa.JSON(), nullable=True),
    sa.Column('is_auto_send', sa.Boolean(), nullable=True),
    sa.Column('available_variables', sa.JSON(), nullable=True),
    sa.Column('variable_description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trigger_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_entities', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_index(op.f('ix_notification_templates_template_code'), 'notification_templates', ['template_code'], unique=True)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('config_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('time_series_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_type', sa.String(length=50), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('period_value', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('previous_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('growth_rate', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_series_trends_id'), 'time_series_trends', ['id'], unique=False)
    op.create_index(op.f('ix_time_series_trends_period_date'), 'time_series_trends', ['period_date'], unique=False)
    op.create_index(op.f('ix_time_series_trends_trend_type'), 'time_series_trends', ['trend_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OFFICER', 'CITIZEN', name='role'), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('identification_number', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('wallet_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_deposited', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_paid_fines', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('pending_fines', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identification_number'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('violation_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('forecast_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_violations', sa.Integer(), nullable=True),
    sa.Column('prediction_confidence', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('upper_bound', sa.Integer(), nullable=True),
    sa.Column('lower_bound', sa.Integer(), nullable=True),
    sa.Column('influencing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violation_forecasts_forecast_date'), 'violation_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_violation_forecasts_id'), 'violation_forecasts', ['id'], unique=False)
    op.create_table('violation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('law_reference', sa.String(length=255), nullable=True),
    sa.Column('fine_min_car', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('fine_max_car', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('points_car', sa.Integer(), nullable=True),
    sa.Column('fine_min_bike', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('fine_max_bike', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('points_bike', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_violation_rules_id'), 'violation_rules', ['id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'UPLOAD', 'DOWNLOAD', 'REVIEW', 'APPROVE', 'REJECT', 'LOGIN', 'LOGOUT', 'FAILED_LOGIN', name='auditaction'), nullable=False),
    sa.Column('resource', sa.Enum('VIDEO', 'DETECTION', 'VIOLATION', 'USER', 'CAMERA', 'AI_CONFIG', 'SYSTEM', name='auditresource'), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('camera_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('has_violations', sa.Boolean(), nullable=True),
    sa.Column('violation_count', sa.Integer(), nullable=True),
    sa.Column('video_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloudinary_public_id')
    )
    op.create_index(op.f('ix_camera_videos_camera_id'), 'camera_videos', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_videos_id'), 'camera_videos', ['id'], unique=False)
    op.create_index(op.f('ix_camera_videos_processing_status'), 'camera_videos', ['processing_status'], unique=False)
    op.create_table('driving_licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_class', sa.Enum('A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'C', 'D', 'E', 'F', name='licenseclass'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('issue_place', sa.String(length=255), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('current_points', sa.Integer(), nullable=True),
    sa.Column('points_reset_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'REVOKED', 'EXPIRED', name='licensestatus'), nullable=True),
    sa.Column('suspension_start', sa.Date(), nullable=True),
    sa.Column('suspension_end', sa.Date(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=500), nullable=True),
    sa.Column('total_violations', sa.Integer(), nullable=True),
    sa.Column('serious_violations', sa.Integer(), nullable=True),
    sa.Column('points_deduction_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_driving_licenses_id'), 'driving_licenses', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_color', sa.String(length=50), nullable=True),
    sa.Column('vehicle_brand', sa.String(length=100), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_identification', sa.String(length=50), nullable=True),
    sa.Column('owner_address', sa.Text(), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('total_violations', sa.Integer(), nullable=True),
    sa.Column('unpaid_violations', sa.Integer(), nullable=True),
    sa.Column('total_fines', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    op.create_index(op.f('ix_vehicles_owner_phone'), 'vehicles', ['owner_phone'], unique=False)
    op.create_table('video_processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('UPLOAD', 'THUMBNAIL', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['camera_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_processing_jobs_id'), 'video_processing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_video_processing_jobs_job_type'), 'video_processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_video_processing_jobs_status'), 'video_processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_video_processing_jobs_video_id'), 'video_processing_jobs', ['video_id'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('vehicle_color', sa.String(length=50), nullable=True),
    sa.Column('vehicle_brand', sa.String(length=100), nullable=True),
    sa.Column('driving_license_id', sa.Integer(), nullable=True),
    sa.Column('violation_type', sa.String(length=100), nullable=False),
    sa.Column('violation_description', sa.Text(), nullable=True),
    sa.Column('violation_rule_id', sa.Integer(), nullable=True),
    sa.Column('points_deducted', sa.Integer(), nullable=True),
    sa.Column('fine_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('legal_reference', sa.String(length=500), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('camera_id', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_images', sa.JSON(), nullable=True),
    sa.Column('evidence_gif', sa.String(length=500), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWING', 'VERIFIED', 'APPROVED', 'REJECTED', 'PAID', 'PROCESSED', name='violationstatus'), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['driving_license_id'], ['driving_licenses.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['camera_videos.id'], ),
    sa.ForeignKeyConstraint(['violation_rule_id'], ['violation_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_id'), 'violations', ['id'], unique=False)
    op.create_index(op.f('ix_violations_license_plate'), 'violations', ['license_plate'], unique=False)
    op.create_index(op.f('ix_violations_video_id'), 'violations', ['video_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_code', sa.String(length=50), nullable=True),
    sa.Column('complainant_name', sa.String(length=255), nullable=False),
    sa.Column('complainant_phone', sa.String(length=20), nullable=True),
    sa.Column('complainant_email', sa.String(length=255), nullable=True),
    sa.Column('complainant_identification', sa.String(length=50), nullable=True),
    sa.Column('complainant_address', sa.Text(), nullable=True),
    sa.Column('complaint_type', sa.Enum('VIOLATION_DISPUTE', 'FALSE_POSITIVE', 'MISSING_VIOLATION', 'OFFICER_BEHAVIOR', 'SYSTEM_ERROR', 'OTHER', name='complainttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', 'CANCELLED', name='complaintstatus'), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('violation_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('desired_resolution', sa.Text(), nullable=True),
    sa.Column('evidence_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('supporting_documents', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('complainant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complainant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_complaint_code'), 'complaints', ['complaint_code'], unique=True)
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_table('denunciations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denunciation_code', sa.String(length=50), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('informant_name', sa.String(length=255), nullable=True),
    sa.Column('informant_phone', sa.String(length=20), nullable=True),
    sa.Column('informant_email', sa.String(length=255), nullable=True),
    sa.Column('informant_identification', sa.String(length=50), nullable=True),
    sa.Column('informant_address', sa.Text(), nullable=True),
    sa.Column('contact_preference', sa.String(length=50), nullable=True),
    sa.Column('can_contact', sa.Boolean(), nullable=True),
    sa.Column('denunciation_type', sa.Enum('CORRUPTION', 'ABUSE_OF_POWER', 'VIOLATION_COVER_UP', 'FRAUD', 'SYSTEM_MANIPULATION', 'OTHER_ILLEGAL', name='denunciationtype'), nullable=False),
    sa.Column('severity_level', sa.String(length=20), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('accused_person_name', sa.String(length=255), nullable=True),
    sa.Column('accused_person_position', sa.String(length=255), nullable=True),
    sa.Column('accused_department', sa.String(length=255), nullable=True),
    sa.Column('related_violation_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('evidence_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFYING', 'INVESTIGATING', 'RESOLVED', 'REJECTED', 'TRANSFERRED', name='denunciationstatus'), nullable=True),
    sa.Column('assigned_investigator_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('investigation_result', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('security_level', sa.String(length=50), nullable=True),
    sa.Column('is_whistleblower', sa.Boolean(), nullable=True),
    sa.Column('transferred_to', sa.String(length=255), nullable=True),
    sa.Column('transfer_reason', sa.Text(), nullable=True),
    sa.Column('transferred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_investigator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denunciations_denunciation_code'), 'denunciations', ['denunciation_code'], unique=True)
    op.create_index(op.f('ix_denunciations_id'), 'denunciations', ['id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('gif_url', sa.String(length=500), nullable=True),
    sa.Column('raw_detection_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_sizes', sa.JSON(), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_violation_id'), 'evidence', ['violation_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Enum('FINE_PAYMENT', 'WALLET_DEPOSIT', 'WALLET_WITHDRAW', 'REFUND', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('original_fine', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('late_penalty', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'PAID', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('WALLET', 'BANK_TRANSFER', 'CREDIT_CARD', 'E_WALLET', 'CASH', 'BANKING', 'QR_CODE', name='paymentmethod'), nullable=True),
    sa.Column('payment_gateway', sa.String(length=100), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('qr_code_data', sa.String(), nullable=True),
    sa.Column('qr_code_image', sa.LargeBinary(), nullable=True),
    sa.Column('qr_transaction_id', sa.String(), nullable=True),
    sa.Column('qr_expiry_time', sa.DateTime(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('transfer_content', sa.String(), nullable=True),
    sa.Column('wallet_balance_before', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('wallet_balance_after', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('payer_identification', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_auto_deduct', sa.Boolean(), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_vehicle_id'), 'payments', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_payments_violation_id'), 'payments', ['violation_id'], unique=False)
    op.create_table('complaint_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_activities_id'), 'complaint_activities', ['id'], unique=False)
    op.create_table('complaint_appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('appeal_code', sa.String(length=50), nullable=True),
    sa.Column('appeal_reason', sa.Text(), nullable=False),
    sa.Column('new_evidence_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='appealstatus'), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_appeals_appeal_code'), 'complaint_appeals', ['appeal_code'], unique=True)
    op.create_index(op.f('ix_complaint_appeals_id'), 'complaint_appeals', ['id'], unique=False)
    op.create_table('denunciation_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denunciation_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['denunciation_id'], ['denunciations.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denunciation_activities_id'), 'denunciation_activities', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_code', sa.String(length=100), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('short_message', sa.String(length=500), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'APP_PUSH', 'WEB_PUSH', 'SYSTEM', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'READ', name='notificationstatus'), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('violation_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('complaint_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('gateway_message_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('template_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_code'), 'notifications', ['notification_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_notification_code'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_denunciation_activities_id'), table_name='denunciation_activities')
    op.drop_table('denunciation_activities')
    op.drop_index(op.f('ix_complaint_appeals_id'), table_name='complaint_appeals')
    op.drop_index(op.f('ix_complaint_appeals_appeal_code'), table_name='complaint_appeals')
    op.drop_table('complaint_appeals')
    op.drop_index(op.f('ix_complaint_activities_id'), table_name='complaint_activities')
    op.drop_table('complaint_activities')
    op.drop_index(op.f('ix_payments_violation_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_vehicle_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_evidence_violation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_denunciations_id'), table_name='denunciations')
    op.drop_index(op.f('ix_denunciations_denunciation_code'), table_name='denunciations')
    op.drop_table('denunciations')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_code'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_violations_video_id'), table_name='violations')
    op.drop_index(op.f('ix_violations_license_plate'), table_name='violations')
    op.drop_index(op.f('ix_violations_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_video_processing_jobs_video_id'), table_name='video_processing_jobs')
    op.drop_index(op.f('ix_video_processing_jobs_status'), table_name='video_processing_jobs')
    op.drop_index(op.f('ix_video_processing_jobs_job_type'), table_name='video_processing_jobs')
    op.drop_index(op.f('ix_video_processing_jobs_id'), table_name='video_processing_jobs')
    op.drop_table('video_processing_jobs')
    op.drop_index(op.f('ix_vehicles_owner_phone'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_driving_licenses_id'), table_name='driving_licenses')
    op.drop_table('driving_licenses')
    op.drop_index(op.f('ix_camera_videos_processing_status'), table_name='camera_videos')
    op.drop_index(op.f('ix_camera_videos_id'), table_name='camera_videos')
    op.drop_index(op.f('ix_camera_videos_camera_id'), table_name='camera_videos')
    op.drop_table('camera_videos')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_violation_rules_id'), table_name='violation_rules')
    op.drop_table('violation_rules')
    op.drop_index(op.f('ix_violation_forecasts_id'), table_name='violation_forecasts')
    op.drop_index(op.f('ix_violation_forecasts_forecast_date'), table_name='violation_forecasts')
    op.drop_table('violation_forecasts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_time_series_trends_trend_type'), table_name='time_series_trends')
    op.drop_index(op.f('ix_time_series_trends_period_date'), table_name='time_series_trends')
    op.drop_index(op.f('ix_time_series_trends_id'), table_name='time_series_trends')
    op.drop_table('time_series_trends')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_notification_templates_template_code'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_model_performance_model_name'), table_name='model_performance')
    op.drop_index(op.f('ix_model_performance_id'), table_name='model_performance')
    op.drop_index(op.f('ix_model_performance_evaluation_date'), table_name='model_performance')
    op.drop_table('model_performance')
    op.drop_index(op.f('ix_location_hotspots_period_date'), table_name='location_hotspots')
    op.drop_index(op.f('ix_location_hotspots_location_name'), table_name='location_hotspots')
    op.drop_index(op.f('ix_location_hotspots_id'), table_name='location_hotspots')
    op.drop_table('location_hotspots')
    op.drop_index(op.f('ix_daily_stats_stat_date'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_confidence_analytics_id'), table_name='confidence_analytics')
    op.drop_index(op.f('ix_confidence_analytics_analysis_date'), table_name='confidence_analytics')
    op.drop_table('confidence_analytics')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
