"""
Detection Log Service for reading AI model detection logs.

This service reads the JSON logs generated by the AI model and provides
detection data for frontend visualization.
"""

import json
import os
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


class DetectionLogService:
    """Service for reading and processing AI detection logs."""
    
    def __init__(self, log_directory: str = "Logs"):
        """Initialize Detection Log Service."""
        self.log_directory = Path(log_directory)
        self.log_cache = {}  # Cache for loaded logs
        
    def get_available_logs(self) -> List[Dict[str, Any]]:
        """
        Get list of available detection log files.
        
        Returns:
            List of log file information
        """
        try:
            if not self.log_directory.exists():
                logger.warning(f"Log directory {self.log_directory} does not exist")
                return []
            
            log_files = []
            for log_file in self.log_directory.glob("detection_log_*.json"):
                try:
                    # Get file stats
                    stat = log_file.stat()
                    
                    # Try to extract timestamp from filename
                    filename = log_file.stem
                    timestamp_str = filename.replace("detection_log_", "")
                    
                    log_info = {
                        "filename": log_file.name,
                        "filepath": str(log_file),
                        "size_bytes": stat.st_size,
                        "created_at": datetime.fromtimestamp(stat.st_ctime).isoformat(),
                        "modified_at": datetime.fromtimestamp(stat.st_mtime).isoformat(),
                        "timestamp_str": timestamp_str
                    }
                    
                    # Try to read basic info from log file
                    try:
                        with open(log_file, 'r', encoding='utf-8') as f:
                            log_data = json.load(f)
                            
                        log_info.update({
                            "video_path": log_data.get("video_info", {}).get("video_path", ""),
                            "total_frames": log_data.get("summary", {}).get("total_frames", 0),
                            "total_vehicles": log_data.get("summary", {}).get("total_vehicles", 0),
                            "max_speed": log_data.get("summary", {}).get("max_speed", 0),
                            "fps": log_data.get("video_info", {}).get("fps", 30)
                        })
                    except Exception as e:
                        logger.warning(f"Could not read log file {log_file}: {e}")
                        
                    log_files.append(log_info)
                    
                except Exception as e:
                    logger.error(f"Error processing log file {log_file}: {e}")
                    continue
            
            # Sort by creation time (newest first)
            log_files.sort(key=lambda x: x["created_at"], reverse=True)
            return log_files
            
        except Exception as e:
            logger.error(f"Error getting available logs: {e}")
            return []
    
    def load_detection_log(self, log_filename: str) -> Optional[Dict[str, Any]]:
        """
        Load a detection log file.
        
        Args:
            log_filename: Name of the log file
            
        Returns:
            Log data or None if not found
        """
        try:
            # Check cache first
            if log_filename in self.log_cache:
                return self.log_cache[log_filename]
            
            log_path = self.log_directory / log_filename
            if not log_path.exists():
                logger.error(f"Log file {log_filename} not found")
                return None
            
            with open(log_path, 'r', encoding='utf-8') as f:
                log_data = json.load(f)
            
            # Cache the loaded data
            self.log_cache[log_filename] = log_data
            
            logger.info(f"Loaded detection log: {log_filename}")
            return log_data
            
        except Exception as e:
            logger.error(f"Error loading detection log {log_filename}: {e}")
            return None
    
    def get_frame_detections(
        self, 
        log_filename: str, 
        frame_number: int
    ) -> Optional[Dict[str, Any]]:
        """
        Get detection data for a specific frame.
        
        Args:
            log_filename: Name of the log file
            frame_number: Frame number to get detections for
            
        Returns:
            Frame detection data or None if not found
        """
        try:
            log_data = self.load_detection_log(log_filename)
            if not log_data:
                return None
            
            # Find the frame in detections
            for frame_data in log_data.get("detections", []):
                if frame_data.get("frame_number") == frame_number:
                    return frame_data
            
            logger.warning(f"Frame {frame_number} not found in log {log_filename}")
            return None
            
        except Exception as e:
            logger.error(f"Error getting frame detections: {e}")
            return None
    
    def get_detections_by_time_range(
        self,
        log_filename: str,
        start_frame: int = 0,
        end_frame: Optional[int] = None,
        limit: int = 1000
    ) -> List[Dict[str, Any]]:
        """
        Get detection data for a range of frames.
        
        Args:
            log_filename: Name of the log file
            start_frame: Starting frame number
            end_frame: Ending frame number (None for all)
            limit: Maximum number of frames to return
            
        Returns:
            List of frame detection data
        """
        try:
            log_data = self.load_detection_log(log_filename)
            if not log_data:
                return []
            
            detections = log_data.get("detections", [])
            
            # Filter by frame range
            filtered_detections = []
            for frame_data in detections:
                frame_num = frame_data.get("frame_number", 0)
                
                if frame_num < start_frame:
                    continue
                    
                if end_frame is not None and frame_num > end_frame:
                    continue
                    
                filtered_detections.append(frame_data)
                
                if len(filtered_detections) >= limit:
                    break
            
            return filtered_detections
            
        except Exception as e:
            logger.error(f"Error getting detections by time range: {e}")
            return []
    
    def get_log_summary(self, log_filename: str) -> Optional[Dict[str, Any]]:
        """
        Get summary information from a log file.
        
        Args:
            log_filename: Name of the log file
            
        Returns:
            Log summary or None if not found
        """
        try:
            log_data = self.load_detection_log(log_filename)
            if not log_data:
                return None
            
            detections = log_data.get("detections", [])
            video_info = log_data.get("video_info", {})
            summary_data = log_data.get("summary", {})
            
            # Calculate additional statistics
            total_vehicles = sum(d.get("vehicle_count", 0) for d in detections)
            total_violations = sum(len(d.get("violations", [])) for d in detections)
            
            summary = {
                "video_info": {
                    "fps": video_info.get("fps"),
                    "width": video_info.get("width"),
                    "height": video_info.get("height"),
                    "source": video_info.get("source")
                },
                "model_info": log_data.get("model_info", {}),
                "summary": {
                    "total_frames": summary_data.get("total_frames", len(detections)),
                    "total_vehicles": summary_data.get("total_vehicles", total_vehicles),
                    "total_violations": summary_data.get("total_violations", total_violations),
                    "detection_frames": len(detections)
                },
                "total_detections": len(detections),
                "detection_frames": [
                    d.get("frame_number") for d in detections
                ]
            }
            
            return summary
            
        except Exception as e:
            logger.error(f"Error getting log summary: {e}")
            return None
    
    def search_violations(
        self,
        log_filename: str,
        violation_type: Optional[str] = None,
        min_speed: Optional[float] = None
    ) -> List[Dict[str, Any]]:
        """
        Search for violations in the log.
        
        Args:
            log_filename: Name of the log file
            violation_type: Type of violation to search for
            min_speed: Minimum speed for violations
            
        Returns:
            List of violation events
        """
        try:
            log_data = self.load_detection_log(log_filename)
            if not log_data:
                return []
            
            violations = []
            
            for frame_data in log_data.get("detections", []):
                frame_violations = frame_data.get("violations", [])
                
                for violation in frame_violations:
                    # Apply filters
                    if violation_type and violation.get("type") != violation_type:
                        continue
                        
                    if min_speed and violation.get("speed", 0) < min_speed:
                        continue
                    
                    # Add frame context
                    violation_with_context = {
                        **violation,
                        "frame_number": frame_data.get("frame_number"),
                        "timestamp": frame_data.get("timestamp"),
                        "frame_vehicle_count": frame_data.get("vehicle_count", 0)
                    }
                    
                    violations.append(violation_with_context)
            
            return violations
            
        except Exception as e:
            logger.error(f"Error searching violations: {e}")
            return []
    
    def get_vehicle_tracks(
        self,
        log_filename: str,
        track_id: Optional[int] = None
    ) -> Dict[int, List[Dict[str, Any]]]:
        """
        Get vehicle tracking data across frames.
        
        Args:
            log_filename: Name of the log file
            track_id: Specific track ID to get (None for all)
            
        Returns:
            Dictionary mapping track_id to list of detections
        """
        try:
            log_data = self.load_detection_log(log_filename)
            if not log_data:
                return {}
            
            tracks = {}
            
            for frame_data in log_data.get("detections", []):
                frame_number = frame_data.get("frame_number")
                
                for detection in frame_data.get("detections", []):
                    det_track_id = detection.get("track_id")
                    
                    if track_id is not None and det_track_id != track_id:
                        continue
                    
                    if det_track_id not in tracks:
                        tracks[det_track_id] = []
                    
                    # Add frame context to detection
                    detection_with_frame = {
                        **detection,
                        "frame_number": frame_number,
                        "timestamp": frame_data.get("timestamp")
                    }
                    
                    tracks[det_track_id].append(detection_with_frame)
            
            return tracks
            
        except Exception as e:
            logger.error(f"Error getting vehicle tracks: {e}")
            return {}


# Global instance
detection_log_service = DetectionLogService()