"""
JSON Log Processor for Real-time AI Detection

This service processes JSON logs generated by the AI detection model
(from Test/main.py) and converts them into real-time detection results
for the WebSocket streaming system.
"""

import json
import asyncio
import logging
from typing import Dict, Any, List, Optional, Callable
from datetime import datetime
from dataclasses import dataclass, asdict
from pathlib import Path
import time

logger = logging.getLogger(__name__)


@dataclass
class LogDetection:
    """Detection data from JSON log."""
    track_id: int
    vehicle_type: str
    bbox: List